### ISSUE TITLE
User Story: Checkout App

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#10]
As an  **online shopper**, I want to **securely complete my purchase using a credit card**, so that I can **efficiently and confidently buy the items in my cart**.

## Tasks:

- [x] Task 1. Create checkout app and templates.

- [x] Task 2. Create an account for Stripe.

- [x] Task 3. Integrate Stripe into the project
