### ISSUE TITLE
User Story: Footer

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#15]
As a **website visitor**, I want to **easily find store information** and have the option to **subscribe to a newsletter**, so that I can **stay informed about the latest updates and promotions.**

## Tasks:

- [x] Task 1. Place store information visibly in the footer.

- [x] Task 2. Sign up to mail chimp.

- [x] Task 3.  Add newsletter to the footer
