### ISSUE TITLE
User Story: User Authentication

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#2]
As a **developer**, I want to **implement user authentication** so that **users can have personalized experiences**.

## Tasks:

- [x] Task 1. Integrate django-allauth for user authentication.

- [x] Task 2. Create authentication views for login, logout, and signup.

- [x] Task 3. Design and implement templates for authentication
