### ISSUE TITLE
User Story: Static and Media Files

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#3]
As a **developer**, I want to **manage static and media files** effectively to ensure **quick page loads and optimized performance**.

## Tasks:

- [x] Task 1. Set up Cloudinary for media storage.

- [x] Task 2. Configure Whitenoise for serving static files.

- [x] Task 3. Test media and static file serving in both development and production settings.
