### ISSUE TITLE
USER STORY: Products

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#7]
As a **developer**, I want to make it **easy to add, view, and organize products**

## Tasks:

- [x] Task 1.  Allow adding new products with names, descriptions, prices, and images.

- [x] Task 2. Create pages where users can see all the products.

- [x] Task 3. Work on the layout and style of the product pages.
