### ISSUE TITLE
USER STORY: Background image

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#8]
As a **developer**, I want to **set an engaging background image for the homepage** to create an **retro feel to the shop**.

## Tasks:

- [x] Task 1. Find a free background image that fits the style of the store.

- [x] Task 2. Ensure the selected background image is of high quality.

- [x] Task 3. Verify that the image is displayed effectively and fits the page layout correctly.
