### ISSUE TITLE
USER STORY: Shopping cart

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/RetroClassics#9]
As a **developer**, I want to implement a **functional shopping cart** and add **styling for a user-friendly appearance.**

## Tasks:

- [x] Task 1. Set up the shopping cart functionality.

- [x] Task 2. Apply basic CSS styles for a clean and usable appearance.

- [x] Task 3. Implement the functionality to display the total price in the shopping cart.
